services:
  web:
    build:
      context: .
      args:
        BUILD_IN: test1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cms

  db:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=directus'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'

  cms:
    image: directus/directus
    ports:
      - "8055:8055"
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "co"
      DB_CLIENT: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "myuser"
      DB_PASSWORD: "secret"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "https://localhost,https://nicolasfritz.dev"
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
    depends_on:
      - db

