name: build and deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  install:
    name: Checkout code and Install dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

  versioning:
    name: Get version
    runs-on: self-hosted
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: |
          VERSION=$(npx semantic-release --dry-run | grep 'nextRelease.version' | sed -E 's/.*"version": "(.*)",/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  build-push:
    name: Build and Push Docker image
    runs-on: self-hosted
    needs: versioning
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: https://nexus.thorge-engelmann.de/repository/docker/
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            https://nexus.thorge-engelmann.de/repository/docker/portfolio:latest,
            https://nexus.thorge-engelmann.de/repository/docker/portfolio:${{ env.VERSION }}
