name: build and deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Build, version, and deploy
    runs-on: self-hosted
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (for semantic-release)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Get version from semantic-release (without publishing)
      - name: Get version
        id: version # ID to reference output
        run: |
          VERSION=$(npx semantic-release --dry-run | grep 'nextRelease.version' | sed -E 's/.*"version": "(.*)",/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Docker image with the new version
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/portfolio:latest,${{ vars.DOCKERHUB_USERNAME }}/portfolio:${{ env.VERSION }}
